project:
  type: website
  output-dir: docs
  resources:
    - "Stanley Xiao Resume.pdf"

website:
  title: "Stanley Xiao"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true